name: Python Tests and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create log directory
      run: |
        mkdir -p post_traces/logs junit

    - name: Run Pylint
      run: |
        for file in $(find . -name "*.py"); do
          pylint "$file" >> post_traces/logs/pylint.log 2>&1
        done

    - name: Run Radon
      run: |
        for file in $(find . -name "*.py"); do
          radon cc -nc "$file" >> post_traces/logs/radon.log 2>&1
        done

    - name: Test with pytest
      run: |
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html > post_traces/logs/pytest.log

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
