name: Python Tests and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create log directory and files
      run: |
        mkdir -p post_traces
        touch post_traces/pylint.log
        touch post_traces/radon.log

    - name: Run Pylint
      run: |
        pylint hw2_debugging.py > post_traces/pylint.log 2>&1 || true
        pylint rand.py >> post_traces/pylint.log 2>&1 || true
        pylint tests.py >> post_traces/pylint.log 2>&1 || true

    - name: Run Radon
      run: |
        radon cc -nc hw2_debugging.py > post_traces/radon.log 2>&1 || true
        radon cc -nc rand.py >> post_traces/radon.log 2>&1 || true
        radon cc -nc tests.py >> post_traces/radon.log 2>&1 || true
    

    - name: Upload Pylint Log
      uses: actions/upload-artifact@v3
      with:
        name: pylint-log
        path: post_traces/pylint.log

    - name: Upload Radon Log
      uses: actions/upload-artifact@v3
      with:
        name: radon-log
        path: post_traces/radon.log

    - name: Test with pytest
      run: |
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html 

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
